import type { ToolCategory_, Tool } from "@/types/tool";

const pdfTools: Tool[] = [
  {
    id: "merge-pdf",
    slug: "merge-pdf",
    category: "pdf",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document",
    metaTitle: "Merge PDF Files Online Free - Combine PDF Documents | ToolNova",
    metaDescription: "Merge multiple PDF files into one document online for free. Combine PDF pages, reorder, and download. No upload required. 100% free.",
    icon: "Combine",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    isPopular: true,
    faq: [
      { question: "How do I merge PDF files?", answer: "Upload your PDF files, arrange them in order, and click Merge. Your combined PDF will be ready instantly." },
      { question: "Is merging PDFs free?", answer: "Yes, merging PDFs on ToolNova is completely free with no limits on file size or number of files." },
      { question: "Are my files secure?", answer: "Yes. All processing happens in your browser. Files are never uploaded to our servers." },
    ],
    relatedTools: ["split-pdf", "compress-pdf", "organize-pdf"],
  },
  {
    id: "split-pdf",
    slug: "split-pdf",
    category: "pdf",
    title: "Split PDF",
    description: "Split PDF files into multiple documents",
    metaTitle: "Split PDF Files Online Free - Separate PDF Pages | ToolNova",
    metaDescription: "Split PDF files into multiple documents online for free. Extract pages, split by range. No upload required. 100% free.",
    icon: "Scissors",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["merge-pdf", "rotate-pdf", "compress-pdf"],
    faq: [
      { question: "How do I split PDF pages?", answer: "Select your PDF, choose the range of pages you want to split or extract, and hit Split. The split file will download immediately." }
    ]
  },
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    category: "pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size without quality loss",
    metaTitle: "Compress PDF Files Online Free - Reduce PDF Size | ToolNova",
    metaDescription: "Compress PDF files online for free. Reduce PDF file size while maintaining quality. No upload required. 100% free.",
    icon: "Scale",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    isPopular: true,
    faq: [
      { question: "How much can I compress a PDF?", answer: "Our compressor can reduce PDF size by up to 80% while maintaining quality." },
      { question: "Is PDF compression free?", answer: "Yes, PDF compression is completely free with no file size limits." },
    ],
    relatedTools: ["merge-pdf", "pdf-to-word", "edit-pdf"],
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    category: "pdf",
    title: "PDF to Word",
    description: "Convert PDF to Word DOC & DOCX documents",
    metaTitle: "Convert PDF to Word Online Free - DOC & DOCX Converter | ToolNova",
    metaDescription: "Convert PDF documents to editable Microsoft Word files instantly for free. 100% client-side conversion, accurate formatting.",
    icon: "FileText",
    color: "text-blue-500",
    bgColor: "bg-blue-50 dark:bg-blue-950/30",
    isPopular: true,
    relatedTools: ["word-to-pdf", "pdf-to-excel", "pdf-to-powerpoint"],
    faq: [
      { question: "Will my Word document format be preserved?", answer: "Yes. ToolNova extracts text layers and structures headers, lists, and tables as closely as possible." }
    ]
  },
  {
    id: "pdf-to-powerpoint",
    slug: "pdf-to-powerpoint",
    category: "pdf",
    title: "PDF to PowerPoint",
    description: "Convert PDF to PowerPoint presentation slides",
    metaTitle: "Convert PDF to PowerPoint Online Free - PPT & PPTX | ToolNova",
    metaDescription: "Convert PDF documents to Microsoft PowerPoint slides online for free. Quick, secure client-side generation.",
    icon: "Sparkles",
    color: "text-orange-500",
    bgColor: "bg-orange-50 dark:bg-orange-950/30",
    relatedTools: ["powerpoint-to-pdf", "pdf-to-word", "pdf-to-excel"],
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    category: "pdf",
    title: "PDF to Excel",
    description: "Extract data and tables from PDF to Excel spreadsheets",
    metaTitle: "Convert PDF to Excel Online Free - PDF to XLS & XLSX | ToolNova",
    metaDescription: "Convert PDF to Excel tables online free. Extract structured tabular data from PDF files to XLS/XLSX or CSV format.",
    icon: "TrendingUp",
    color: "text-green-500",
    bgColor: "bg-green-50 dark:bg-green-950/30",
    relatedTools: ["excel-to-pdf", "pdf-to-word", "pdf-to-markdown"],
  },
  {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    category: "pdf",
    title: "Word to PDF",
    description: "Convert DOC & DOCX documents to PDF format",
    metaTitle: "Convert Word to PDF Online Free - DOC/DOCX to PDF | ToolNova",
    metaDescription: "Convert Microsoft Word documents (DOC and DOCX) to PDF online for free. Instant client-side conversions.",
    icon: "FileText",
    color: "text-blue-600",
    bgColor: "bg-blue-50 dark:bg-blue-900/10",
    relatedTools: ["pdf-to-word", "powerpoint-to-pdf", "excel-to-pdf"],
  },
  {
    id: "powerpoint-to-pdf",
    slug: "powerpoint-to-pdf",
    category: "pdf",
    title: "PowerPoint to PDF",
    description: "Convert PowerPoint presentations to PDF format",
    metaTitle: "Convert PPT/PPTX to PDF Online Free - Presentation to PDF | ToolNova",
    metaDescription: "Convert PowerPoint slides (PPT, PPTX) to PDF documents online for free. Secure offline-capable conversion.",
    icon: "Sparkles",
    color: "text-orange-600",
    bgColor: "bg-orange-50 dark:bg-orange-900/10",
    relatedTools: ["pdf-to-powerpoint", "word-to-pdf", "excel-to-pdf"],
  },
  {
    id: "excel-to-pdf",
    slug: "excel-to-pdf",
    category: "pdf",
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF format",
    metaTitle: "Convert Excel to PDF Online Free - XLS/XLSX to PDF | ToolNova",
    metaDescription: "Convert Excel spreadsheets (XLS, XLSX) to PDF documents online for free. Secure, clean client-side translation.",
    icon: "TrendingUp",
    color: "text-green-600",
    bgColor: "bg-green-50 dark:bg-green-900/10",
    relatedTools: ["pdf-to-excel", "word-to-pdf", "powerpoint-to-pdf"],
  },
  {
    id: "edit-pdf",
    slug: "edit-pdf",
    category: "pdf",
    title: "Edit PDF",
    description: "Edit text, images, and pages in PDF files",
    metaTitle: "Edit PDF Files Online Free - PDF Editor | ToolNova",
    metaDescription: "Edit PDF files online for free. Add text, images, annotations, and signatures.",
    icon: "FileEdit",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["merge-pdf", "sign-pdf", "redact-pdf"],
  },
  {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    category: "pdf",
    title: "PDF to JPG",
    description: "Convert each PDF page into a separate JPG image",
    metaTitle: "Convert PDF to JPG Online Free - Extract PDF Pages to Images | ToolNova",
    metaDescription: "Convert PDF pages to JPG images in seconds online for free. Extract all images embedded in your PDF document. 100% client-side.",
    icon: "Image",
    color: "text-amber-500",
    bgColor: "bg-amber-50 dark:bg-amber-950/30",
    isPopular: true,
    relatedTools: ["jpg-to-pdf", "pdf-to-word", "crop-pdf"],
  },
  {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    category: "pdf",
    title: "JPG to PDF",
    description: "Convert JPG and PNG images to PDF files",
    metaTitle: "Convert JPG to PDF Online Free - Images to PDF | ToolNova",
    metaDescription: "Convert JPG, PNG, and WebP images to PDF files online for free. Adjust page orientation, size, and margins easily in your browser.",
    icon: "Image",
    color: "text-emerald-500",
    bgColor: "bg-emerald-50 dark:bg-emerald-950/30",
    relatedTools: ["pdf-to-jpg", "merge-pdf", "crop-pdf"],
  },
  {
    id: "sign-pdf",
    slug: "sign-pdf",
    category: "pdf",
    title: "Sign PDF",
    description: "Add signatures and initials to PDF documents",
    metaTitle: "Sign PDF Documents Online Free - Electronic Signature | ToolNova",
    metaDescription: "Sign PDF documents online for free. Add electronic signatures, initials, and dates.",
    icon: "Pen",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["edit-pdf", "protect-pdf", "merge-pdf"],
  },
  {
    id: "add-watermark-pdf",
    slug: "add-watermark-pdf",
    category: "pdf",
    title: "Add Watermark",
    description: "Add text or image watermark to PDF",
    metaTitle: "Add Watermark to PDF Online Free - PDF Watermark | ToolNova",
    metaDescription: "Add text or image watermarks to PDF files online for free. Protect your PDF documents.",
    icon: "Palette",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["protect-pdf", "sign-pdf", "edit-pdf"],
  },
  {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    category: "pdf",
    title: "Rotate PDF",
    description: "Rotate PDF pages to the correct orientation",
    metaTitle: "Rotate PDF Pages Online Free - PDF Rotator | ToolNova",
    metaDescription: "Rotate PDF pages online for free. Fix page orientation in PDF documents.",
    icon: "RotateCw",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["merge-pdf", "split-pdf", "edit-pdf"],
  },
  {
    id: "html-to-pdf",
    slug: "html-to-pdf",
    category: "pdf",
    title: "HTML to PDF",
    description: "Convert HTML content or webpage URL to PDF document",
    metaTitle: "HTML to PDF Converter Online Free - URL to PDF | ToolNova",
    metaDescription: "Convert HTML webpages, files, or markup code into high-quality PDF files online for free. Fully client-side processing.",
    icon: "Globe",
    color: "text-teal-500",
    bgColor: "bg-teal-50 dark:bg-teal-950/30",
    relatedTools: ["pdf-to-markdown", "pdf-to-word", "pdf-to-jpg"],
  },
  {
    id: "unlock-pdf",
    slug: "unlock-pdf",
    category: "pdf",
    title: "Unlock PDF",
    description: "Remove password and restrictions from PDF files",
    metaTitle: "Unlock PDF Files Online Free - Remove PDF Password | ToolNova",
    metaDescription: "Remove password protection from PDF files online for free. Unlock secured PDF documents.",
    icon: "Unlock",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    isPopular: true,
    relatedTools: ["protect-pdf", "compress-pdf", "edit-pdf"],
  },
  {
    id: "protect-pdf",
    slug: "protect-pdf",
    category: "pdf",
    title: "Protect PDF",
    description: "Add password protection to PDF files",
    metaTitle: "Protect PDF with Password Online Free - PDF Security | ToolNova",
    metaDescription: "Add password protection to PDF files online for free. Encrypt and secure PDF documents.",
    icon: "Lock",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["compress-pdf", "edit-pdf", "sign-pdf"],
  },
  {
    id: "organize-pdf",
    slug: "organize-pdf",
    category: "pdf",
    title: "Organize PDF",
    description: "Reorder, delete, and insert PDF pages",
    metaTitle: "Organize PDF Pages Online Free - PDF Page Organizer | ToolNova",
    metaDescription: "Organize PDF pages online for free. Reorder, delete, and insert pages in your PDF document.",
    icon: "FolderTree",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    isPopular: true,
    relatedTools: ["merge-pdf", "split-pdf", "rotate-pdf"],
  },
  {
    id: "pdf-to-pdfa",
    slug: "pdf-to-pdfa",
    category: "pdf",
    title: "PDF to PDF/A",
    description: "Convert PDF to PDF/A for long-term archiving",
    metaTitle: "Convert PDF to PDF/A Online Free - ISO Standardization | ToolNova",
    metaDescription: "Convert your PDF files to PDF/A standard format online for free. Preserve formatting, fonts, and structures permanently.",
    icon: "BookOpen",
    color: "text-rose-500",
    bgColor: "bg-rose-50 dark:bg-rose-950/30",
    relatedTools: ["repair-pdf", "protect-pdf", "compress-pdf"],
  },
  {
    id: "repair-pdf",
    slug: "repair-pdf",
    category: "pdf",
    title: "Repair PDF",
    description: "Repair damaged PDF files and recover data",
    metaTitle: "Repair Damaged PDF Files Online Free - Fix Corrupted PDF | ToolNova",
    metaDescription: "Repair corrupted or damaged PDF documents online for free. Reconstruct broken layouts and cross-reference tables locally.",
    icon: "Wrench",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["compress-pdf", "organize-pdf", "pdf-to-pdfa"],
  },
  {
    id: "add-page-numbers-pdf",
    slug: "add-page-numbers-pdf",
    category: "pdf",
    title: "Add Page Numbers",
    description: "Add page numbers to PDF documents",
    metaTitle: "Add Page Numbers to PDF Online Free | ToolNova",
    metaDescription: "Add page numbers to PDF documents online for free. Customize position, style, and font.",
    icon: "Hash",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["edit-pdf", "merge-pdf", "organize-pdf"],
  },
  {
    id: "scan-to-pdf",
    slug: "scan-to-pdf",
    category: "pdf",
    title: "Scan to PDF",
    description: "Convert device camera captures into PDF documents",
    metaTitle: "Scan Documents to PDF Online Free - Mobile Camera Scanner | ToolNova",
    metaDescription: "Scan documents using your webcam or mobile device camera and compile them instantly into a PDF file with filters. 100% free.",
    icon: "Camera",
    color: "text-violet-500",
    bgColor: "bg-violet-50 dark:bg-violet-950/30",
    relatedTools: ["jpg-to-pdf", "ocr-pdf", "merge-pdf"],
  },
  {
    id: "ocr-pdf",
    slug: "ocr-pdf",
    category: "pdf",
    title: "OCR PDF",
    description: "Convert scanned PDF to searchable text",
    metaTitle: "OCR PDF Online Free - Convert Scanned PDF to Text | ToolNova",
    metaDescription: "Convert scanned PDF documents into searchable and selectable text with OCR online for free.",
    icon: "ScanText",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    isNew: true,
    relatedTools: ["pdf-to-word", "smart-summary", "translate-pdf"],
  },
  {
    id: "compare-pdf",
    slug: "compare-pdf",
    category: "pdf",
    title: "Compare PDF",
    description: "Compare two PDF documents side by side",
    metaTitle: "Compare PDF Files Online Free - PDF Diff Tool | ToolNova",
    metaDescription: "Compare two PDF documents side by side and find differences online for free.",
    icon: "GitCompare",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["merge-pdf", "edit-pdf", "organize-pdf"],
  },
  {
    id: "redact-pdf",
    slug: "redact-pdf",
    category: "pdf",
    title: "Redact PDF",
    description: "Permanently hide sensitive information in PDF",
    metaTitle: "Redact PDF Online Free - Remove Sensitive Info | ToolNova",
    metaDescription: "Redact text and images to permanently remove sensitive information from PDF documents online for free.",
    icon: "Eraser",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["protect-pdf", "sign-pdf", "edit-pdf"],
  },
  {
    id: "crop-pdf",
    slug: "crop-pdf",
    category: "pdf",
    title: "Crop PDF",
    description: "Crop margins from PDF documents",
    metaTitle: "Crop PDF Online Free - Trim PDF Margins | ToolNova",
    metaDescription: "Crop and trim margins from PDF documents online for free. Remove unwanted white space.",
    icon: "Crop",
    color: "text-red-500",
    bgColor: "bg-red-50 dark:bg-red-950/30",
    relatedTools: ["edit-pdf", "rotate-pdf", "organize-pdf"],
  },
  {
    id: "pdf-forms",
    slug: "pdf-forms",
    category: "pdf",
    title: "PDF Forms",
    description: "Fill out PDF forms or add interactive form fields",
    metaTitle: "Fill & Create PDF Forms Online Free - Interactive PDFs | ToolNova",
    metaDescription: "Fill out interactive PDF forms or add new text fields, check boxes, radio buttons, and dropdowns client-side.",
    icon: "CheckSquare",
    color: "text-indigo-500",
    bgColor: "bg-indigo-50 dark:bg-indigo-950/30",
    isNew: true,
    relatedTools: ["edit-pdf", "sign-pdf", "protect-pdf"],
  },
  {
    id: "smart-summary",
    slug: "smart-summary",
    category: "pdf",
    title: "Smart Summary",
    description: "Generate intelligent summaries from long documents",
    metaTitle: "Smart Summary - AI PDF Summarizer Online Free | ToolNova",
    metaDescription: "Extract text from articles, reports, or PDF books and generate concise summaries using local processing. 100% secure.",
    icon: "Cpu",
    color: "text-fuchsia-500",
    bgColor: "bg-fuchsia-50 dark:bg-fuchsia-950/30",
    isNew: true,
    relatedTools: ["ocr-pdf", "translate-pdf", "pdf-to-markdown"],
  },
  {
    id: "translate-pdf",
    slug: "translate-pdf",
    category: "pdf",
    title: "Translate PDF",
    description: "Translate PDF document paragraphs using local processing",
    metaTitle: "Translate PDF Online Free - Local Document Translator | ToolNova",
    metaDescription: "Translate text content from your PDF documents into various languages locally while keeping layouts intact. No registration required.",
    icon: "Languages",
    color: "text-cyan-500",
    bgColor: "bg-cyan-50 dark:bg-cyan-950/30",
    isNew: true,
    relatedTools: ["ocr-pdf", "smart-summary", "pdf-to-word"],
  },
  {
    id: "pdf-to-markdown",
    slug: "pdf-to-markdown",
    category: "pdf",
    title: "PDF to Markdown",
    description: "Convert PDF text layouts into GFM Markdown syntax",
    metaTitle: "Convert PDF to Markdown Online Free - PDF to MD | ToolNova",
    metaDescription: "Convert PDF text structure, tables, and lists into clear GitHub Flavored Markdown (MD) files online for free. Fast client-side extractor.",
    icon: "Code",
    color: "text-pink-500",
    bgColor: "bg-pink-50 dark:bg-pink-950/30",
    isNew: true,
    relatedTools: ["pdf-to-word", "pdf-to-excel", "smart-summary"],
  },
  {
    id: "custom-workflow",
    slug: "custom-workflow",
    category: "pdf",
    title: "Custom Workflow",
    description: "Chain multiple PDF tools in a single automated process",
    metaTitle: "Custom PDF Workflows - Chain PDF Actions Online | ToolNova",
    metaDescription: "Build sequential pipelines for processing PDF documents (e.g. Merge -> Compress -> Protect) in one go. Free and local.",
    icon: "Workflow",
    color: "text-purple-500",
    bgColor: "bg-purple-50 dark:bg-purple-950/30",
    relatedTools: ["merge-pdf", "compress-pdf", "protect-pdf"],
  },
];

export const categories: ToolCategory_[] = [
  {
    id: "pdf",
    slug: "pdf",
    title: "PDF Tools",
    description: "Free online PDF tools to merge, split, compress, convert, and edit PDF files.",
    metaTitle: "Free PDF Tools Online - Merge, Compress, Convert & Edit PDFs | ToolNova",
    metaDescription: "Free online PDF tools. Merge PDFs, compress PDF files, convert PDF to Word/Excel/JPG, edit PDF text and images.",
    icon: "FileText",
    color: "text-red-500",
    tools: pdfTools,
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  for (const category of categories) {
    const tool = category.tools.find((t) => t.slug === slug);
    if (tool) return tool;
  }
  return undefined;
}

export function getToolsByCategory(categoryId: string): Tool[] {
  const category = categories.find((c) => c.id === categoryId);
  return category?.tools ?? [];
}

export function getCategoryById(categoryId: string): ToolCategory_ | undefined {
  return categories.find((c) => c.id === categoryId);
}

export function getCategoryBySlug(slug: string): ToolCategory_ | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getPopularTools(): Tool[] {
  return categories.flatMap((c) => c.tools).filter((t) => t.isPopular);
}

export function getNewTools(): Tool[] {
  return categories.flatMap((c) => c.tools).filter((t) => t.isNew);
}

export const toolTranslationKeys: Record<string, string> = {
  "merge-pdf": "pdf.tools.merge",
  "split-pdf": "pdf.tools.split",
  "compress-pdf": "pdf.tools.compress",
  "pdf-to-word": "pdf.tools.pdfToWord",
  "pdf-to-powerpoint": "pdf.tools.pdfToPowerpoint",
  "pdf-to-excel": "pdf.tools.pdfToExcel",
  "word-to-pdf": "pdf.tools.wordToPdf",
  "powerpoint-to-pdf": "pdf.tools.powerpointToPdf",
  "excel-to-pdf": "pdf.tools.excelToPdf",
  "edit-pdf": "pdf.tools.edit",
  "pdf-to-jpg": "pdf.tools.pdfToJpg",
  "jpg-to-pdf": "pdf.tools.jpgToPdf",
  "sign-pdf": "pdf.tools.sign",
  "add-watermark-pdf": "pdf.tools.watermark",
  "rotate-pdf": "pdf.tools.rotate",
  "html-to-pdf": "pdf.tools.htmlToPdf",
  "unlock-pdf": "pdf.tools.unlock",
  "protect-pdf": "pdf.tools.protect",
  "organize-pdf": "pdf.tools.organize",
  "pdf-to-pdfa": "pdf.tools.pdfToPdfa",
  "repair-pdf": "pdf.tools.repair",
  "add-page-numbers-pdf": "pdf.tools.pageNumbers",
  "scan-to-pdf": "pdf.tools.scanToPdf",
  "ocr-pdf": "pdf.tools.ocr",
  "compare-pdf": "pdf.tools.compare",
  "redact-pdf": "pdf.tools.redact",
  "crop-pdf": "pdf.tools.crop",
  "pdf-forms": "pdf.tools.pdfForms",
  "smart-summary": "pdf.tools.smartSummary",
  "translate-pdf": "pdf.tools.translatePdf",
  "pdf-to-markdown": "pdf.tools.pdfToMarkdown",
  "custom-workflow": "pdf.tools.customWorkflow",
};

export function getTranslationKeys(toolId: string): string {
  return toolTranslationKeys[toolId] || "";
}

export function getCategoryTranslationKey(catId: string): string {
  return "common.nav.pdf";
}
